{{- if or ( eq .Values.global.create "AllExceptPVCPV" ) ( eq .Values.global.create "All" ) }}

{{- if .Values.container }}
{{- if .Values.container.serverName }}
{{- if .Values.container.secretenv }}

{{$replicas:= include "container.replicas" . }}
{{- if ne $replicas "0" }}


apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ .Release.Name }}-{{ .Values.container.serverName | camelcase | lower }}"
  labels:
    app: "{{ .Release.Name | lower }}-{{ .Values.container.serverName | lower }}"
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:

{{- range $key, $value := .Values.container.secretenv }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}

{{- end }}

{{- end }}
{{- end }}
{{- end }}

{{- end }}
