{{- if or ( eq .Values.global.create "AllExceptPVCPV" ) ( eq .Values.global.create "All" ) }}

{{- if .Values.global.serviceAccount }}
{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container.serviceAccountName" . }}
  labels:
    {{- include "container.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{- end }}
